import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createMusicClient } from '@llm-music/api-client';
import { test, expect } from '@playwright/test';
import { runDir, labels, inputs, completedCandidate, mediaState, control, received } from './generation-fixtures.js';

test.beforeEach(async () => { await control({}); });

test('first player module transport failure can explicitly retry without losing reference selection or draft', async ({ page, baseURL }) => {
  if (!baseURL) throw new Error('No owned URL');
  const api = createMusicClient({ baseUrl: `${baseURL}/api` });
  const project = received(await api.POST('/projects', { body: { name: '播放器初始化恢复 · CPU' } }));
  const firstFailure = page.waitForEvent('requestfailed', { predicate: request => request.url().includes('wavesurfer') });
  await page.route('**/*wavesurfer*', route => route.abort('failed'));
  await page.goto(`/projects/${project.id}/generate`);
  await firstFailure;
  const originalAudio = await page.locator('audio').elementHandle();
  if (!originalAudio) throw new Error('No original native audio element');
  await page.getByRole('combobox').selectOption('en');
  await inputs(page, 'en');
  await page.unroute('**/*wavesurfer*');
  await page.getByRole('link', { name: 'Reference audio and assets', exact: true }).click();
  const referencePath = fileURLToPath(new URL('../../docs/previews/web-mvp-v1/reference-16s.wav', import.meta.url));
  await page.getByLabel('Choose WAV audio').setInputFiles(referencePath);
  await page.getByRole('button', { name: 'Add to project assets' }).click();
  await expect(page.getByRole('region', { name: 'Asset details' }).getByRole('heading', { name: 'reference-16s.wav', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Reference transcription', exact: true }).click();
  await page.getByRole('button', { name: 'Listen to selected reference' }).click();
  const player = page.locator('#persistent-player');
  await expect(player.getByRole('button', { name: 'Reread audio' })).toBeVisible();
  await expect(player.getByText('reference-16s.wav', { exact: true })).toBeVisible();
  await player.getByRole('button', { name: 'Reread audio' }).click();
  await expect(player.getByRole('button', { name: 'Play', exact: true })).toBeEnabled();
  expect(await originalAudio.evaluate(element => element === document.querySelector('audio'))).toBe(true);
  await expect(page.locator('audio')).toHaveCount(1);
  await expect.poll(async () => (await mediaState(page)).duration).toBe(16);
  await player.getByRole('button', { name: 'Play', exact: true }).click();
  await expect.poll(async () => (await mediaState(page)).time).toBeGreaterThan(0.15);
  const before = (await mediaState(page)).time;
  await page.getByRole('link', { name: 'Generate music', exact: true }).click();
  await expect(page.getByRole('textbox', { name: labels.en.style, exact: true })).toHaveValue('温暖的钢琴 · warm piano');
  await expect(page.getByRole('textbox', { name: labels.en.seed, exact: true })).toHaveValue('2026192201');
  await expect.poll(async () => (await mediaState(page)).time).toBeGreaterThan(before);
  expect((await mediaState(page)).paused).toBe(false);
  expect(await originalAudio.evaluate(element => element === document.querySelector('audio'))).toBe(true);
});

test('OOM, model, workflow, cancellation and readiness failures preserve editable input; retry is explicit', async ({ page, baseURL }) => {
  if (!baseURL) throw new Error('No owned URL');
  const api = createMusicClient({ baseUrl: `${baseURL}/api` });
  const project = received(await api.POST('/projects', { body: { name: '恢复生成 · controlled CPU' } }));
  const path = { project_id: project.id };
  await page.goto(`/projects/${project.id}/generate`);
  await page.getByRole('combobox').selectOption('en');
  await inputs(page, 'en');
  for (const scenario of ['runtime_out_of_memory', 'model_missing', 'workflow_invalid', 'generation_failed']) {
    await control({ scenario });
    await page.getByRole('button', { name: labels.en.submit }).click();
    await expect(page.locator('.job-problem')).toContainText(scenario);
    await expect(page.getByRole('textbox', { name: labels.en.seed, exact: true })).toHaveValue('2026192201');
    expect(received(await api.GET('/projects/{project_id}/candidates', { params: { path } }))).toEqual([]);
    expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([]);
  }
  await control({ scenario: 'hold' });
  await page.getByRole('button', { name: labels.en.submit }).click();
  await expect(page.getByText('Progress is unknown; showing the current phase')).toBeVisible();
  await expect(page.getByRole('progressbar')).toHaveCount(0);
  await page.getByRole('button', { name: 'Request cancellation' }).click();
  await expect(page.locator('.job-card .tag')).toHaveText('Cancelled');
  await expect(page.getByRole('textbox', { name: labels.en.lyrics, exact: true })).toHaveValue('[Verse]\n雨停之后，我们走向晨光。\nAfter rain, we walk into morning.');
  await expect(page.getByRole('textbox', { name: labels.en.style, exact: true })).toHaveValue('温暖的钢琴 · warm piano');
  await control({});
  const oldJobs = received(await api.GET('/projects/{project_id}/jobs', { params: { path } }));
  await page.getByRole('button', { name: 'Create a new retry job' }).click();
  await expect(page.locator('[data-candidate-id]')).toBeVisible();
  const jobs = received(await api.GET('/projects/{project_id}/jobs', { params: { path } }));
  expect(jobs).toHaveLength(oldJobs.length + 1);
  expect(jobs.at(-1)?.provenance.retry_of_job_id).toBe(oldJobs.at(-1)?.id);
  await control({ capability: 'missing' });
  await page.reload();
  await expect(page.getByRole('button', { name: labels.en.submit })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: labels.en.style, exact: true })).toHaveValue('温暖的钢琴 · warm piano');
});

test('save failure keeps candidate/name; lost durable acknowledgement recovers one version; damaged media can reread', async ({ page, baseURL }) => {
  if (!baseURL) throw new Error('No owned URL');
  const api = createMusicClient({ baseUrl: `${baseURL}/api` });
  const project = received(await api.POST('/projects', { body: { name: '保存与试听恢复 · CPU' } }));
  const path = { project_id: project.id };
  await page.goto(`/projects/${project.id}/generate`);
  await page.getByRole('combobox').selectOption('en');
  await inputs(page, 'en');
  const candidateId = await completedCandidate(page, 'en');
  const candidate = received(await api.GET('/projects/{project_id}/candidates/{candidate_id}', { params: { path: { ...path, candidate_id: candidateId } } }));
  await page.getByRole('textbox', { name: labels.en.name, exact: true }).fill('保留这个名字');
  await writeFile(resolve(runDir!, 'fail-version-save'), 'owned test fault');
  await page.getByRole('button', { name: labels.en.save, exact: true }).click();
  await expect(page.locator('.save-candidate .error-box')).toContainText('version_commit_unconfirmed');
  await expect(page.getByRole('textbox', { name: labels.en.name, exact: true })).toHaveValue('保留这个名字');
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([]);
  await writeFile(resolve(runDir!, 'lose-version-ack'), 'owned test fault');
  await page.getByRole('button', { name: labels.en.save, exact: true }).click();
  await expect(page.locator('.save-candidate .error-box')).toContainText('version_commit_unconfirmed');
  await page.getByRole('button', { name: 'Reread saved versions' }).click();
  await expect(page.getByRole('link', { name: labels.en.saved })).toBeVisible();
  const versions = received(await api.GET('/projects/{project_id}/versions', { params: { path } }));
  expect(versions).toHaveLength(1);
  const asset = received(await api.GET('/projects/{project_id}/assets/{asset_id}', { params: { path: { ...path, asset_id: candidate.audio_asset_id } } }));
  const file = resolve(runDir!, 'application', 'assets', project.id, `${asset.id}.${asset.format}`);
  const bytes = await readFile(file);
  await writeFile(file, Buffer.alloc(bytes.length));
  await page.getByRole('button', { name: labels.en.listen }).click();
  await expect(page.locator('#persistent-player [role=alert]')).toContainText('This audio could not play');
  await expect(page.getByRole('textbox', { name: labels.en.style, exact: true })).toHaveValue(candidate.inputs.style);
  await writeFile(file, bytes);
  await page.getByRole('button', { name: 'Reread audio' }).click();
  await expect(page.locator('#persistent-player').getByRole('button', { name: labels.en.play, exact: true })).toBeEnabled();
  await page.reload();
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual(versions);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: labels.en.listen }).click();
  const player = page.locator('#persistent-player');
  await expect(player.getByRole('button', { name: labels.en.play, exact: true })).toBeEnabled();
  await player.getByText(labels.en.region, { exact: true }).click();
  await player.getByLabel(labels.en.start, { exact: true }).fill('1');
  await player.getByLabel(labels.en.end, { exact: true }).fill('2');
  await player.getByRole('button', { name: labels.en.apply }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await expect(page.locator('audio')).toHaveCount(1);
});
