import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { expect, test } from '@playwright/test';
import type { JobRead } from '@llm-music/api-client';
import { control, hash, mediaState, runDir } from './generation-fixtures.js';
import { ABC, EDITED_ABC, NEXT_ABC, downloadMidi, expectMusic, received, seed } from './score-fixtures.js';
import { LYRICS, SEED, STYLE, fillGeneration, generateCandidate, selectEdited, translations, withParent } from './score-generation-fixtures.js';

test.beforeEach(async () => { await control({}); });

test('a lost Version acknowledgement retains the first name, Candidate and parent despite later name edits', async ({ page, baseURL }, info) => {
  const { api, project, score, original } = await withParent(baseURL);
  const selected = await selectEdited(page, project.id, score.id);
  const candidateId = await generateCandidate(page);
  const path = { project_id: project.id };
  const firstName = 'Keep the first submitted name';
  const writes: unknown[] = [];
  let drop = true;
  await page.route(`**/api/projects/${project.id}/versions`, async route => {
    if (route.request().method() !== 'POST') return route.continue();
    writes.push(route.request().postDataJSON());
    const response = await route.fetch();
    if (drop) { drop = false; await route.abort('failed'); }
    else await route.fulfill({ response });
  });
  await page.getByRole('textbox', { name: 'Version name', exact: true }).fill(firstName);
  await page.getByRole('button', { name: 'Save as a version', exact: true }).click();
  await expect(page.locator('.save-candidate .error-box')).toBeVisible();
  const committed = received(await api.GET('/projects/{project_id}/versions', { params: { path } }));
  expect(committed).toHaveLength(2);
  const derived = committed.find(value => value.id !== original.id);
  if (!derived) throw new Error('No durably committed Version before the lost ACK');
  expect(derived).toMatchObject({ name: firstName, candidate_id: candidateId, parent_version_id: original.id });
  await page.getByRole('textbox', { name: 'Version name', exact: true }).fill('A later textbox edit must not change the intent');
  const retry = page.getByRole('button', { name: 'Save the same version again', exact: true });
  await expect(retry).toBeVisible();
  await retry.click();
  await expect(page.getByRole('link', { name: 'View saved version', exact: true })).toBeVisible();
  expect(writes).toEqual([{ candidate_id: candidateId, name: firstName }, { candidate_id: candidateId, name: firstName }]);
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual(committed);
  expect(derived.inputs).toMatchObject({ abc: EDITED_ABC, source_score_id: selected, parent_version_id: original.id });
  await info.attach('captured-version-save', { body: JSON.stringify({ writes, original, derived }, null, 2), contentType: 'application/json' });
});

for (const locale of ['en', 'zh-CN'] as const) for (const theme of ['light', 'dark'] as const) {
  test(`${locale}/${theme}: edited selection generates its exact snapshot, plays in the sole Player and explicitly saves a child Version`, async ({ page, baseURL }, info) => {
    const { api, project, score, original } = await withParent(baseURL);
    const path = { project_id: project.id }, t = translations[locale];
    const errors: string[] = [], requests: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => requests.push(request.url()));
    const originalAudio = received(await api.GET('/projects/{project_id}/assets/{asset_id}/content', { params: { path: { ...path, asset_id: original.audio_asset_id } }, parseAs: 'arrayBuffer' }));
    const selected = await selectEdited(page, project.id, score.id, locale);
    if (await page.locator('html').getAttribute('data-theme') !== theme) await page.locator('.preferences button').click();
    await expect(page.locator('html')).toHaveAttribute('lang', locale);
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
    await page.setViewportSize({ width: theme === 'dark' ? 390 : 1440, height: 960 });
    const midi = await downloadMidi(page, locale === 'en' ? 'Export draft MIDI' : '导出草稿 MIDI');
    expectMusic(midi, true);
    const posted = page.waitForRequest(request => request.method() === 'POST' && request.url().endsWith('/jobs/generate-from-score'));
    const candidateId = await generateCandidate(page, locale);
    const body: unknown = (await posted).postDataJSON();
    expect(body).toEqual({ abc: EDITED_ABC, source_score_id: selected, parent_version_id: original.id, style: STYLE, lyrics: LYRICS, seed: Number(SEED), max_seconds: 35 });
    const candidate = received(await api.GET('/projects/{project_id}/candidates/{candidate_id}', { params: { path: { ...path, candidate_id: candidateId } } }));
    const job = received(await api.GET('/projects/{project_id}/jobs/{job_id}', { params: { path: { ...path, job_id: candidate.job_id } } }));
    expect(job).toMatchObject({ operation: 'GenerateFromScore', status: 'completed', inputs: body });
    expect(candidate.inputs).toEqual(body);
    expect(candidate.inputs).toMatchObject({ parent_version_id: original.id });
    expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([original]);
    const outputScore = received(await api.GET('/projects/{project_id}/scores/{score_id}', { params: { path: { ...path, score_id: candidate.score_id } } }));
    expect(received(await api.GET('/projects/{project_id}/assets/{asset_id}/content', { params: { path: { ...path, asset_id: outputScore.abc_asset_id } }, parseAs: 'text' }))).toBe(EDITED_ABC);
    const audio = received(await api.GET('/projects/{project_id}/assets/{asset_id}', { params: { path: { ...path, asset_id: candidate.audio_asset_id } } }));
    const player = page.locator('#persistent-player');
    const native = await player.locator('audio').elementHandle();
    if (!native) throw new Error('No sole native Player');
    await page.getByRole('button', { name: t.listen, exact: true }).click();
    await expect(player.getByRole('button', { name: t.play, exact: true })).toBeEnabled();
    await expect.poll(async () => (await mediaState(page)).duration).toBeCloseTo(34.9986667, 4);
    await player.getByRole('button', { name: t.play, exact: true }).click();
    await expect.poll(async () => (await mediaState(page)).time).toBeGreaterThan(.1);
    const before = (await mediaState(page)).time;
    const source = await player.locator('audio').getAttribute('src');
    await page.getByRole('link', { name: t.inputs, exact: true }).click();
    await expect.poll(async () => (await mediaState(page)).time).toBeGreaterThan(before);
    await page.getByRole('link', { name: t.versions, exact: true }).click();
    await expect(page.locator('audio')).toHaveCount(1);
    expect(await native.evaluate(element => element === document.querySelector('#persistent-player audio'))).toBe(true);
    await expect(player.locator('audio')).toHaveAttribute('src', source!);
    expect((await mediaState(page)).paused).toBe(false);
    await page.getByRole('link', { name: t.scores, exact: true }).click();
    await page.locator(`a[href="/projects/${project.id}/scores/${score.id}"]`).click();
    await expect(page.locator('.candidate-detail')).toHaveAttribute('data-candidate-id', candidateId);
    const name = `New melody · ${locale}/${theme}`;
    await page.getByRole('textbox', { name: t.name, exact: true }).fill(name);
    await page.getByRole('button', { name: t.save, exact: true }).click();
    await page.getByRole('link', { name: t.saved, exact: true }).click();
    const versions = received(await api.GET('/projects/{project_id}/versions', { params: { path } }));
    expect(versions).toHaveLength(2);
    const child = versions.find(value => value.id !== original.id);
    if (!child) throw new Error('No explicit child Version');
    expect(child).toMatchObject({ name, candidate_id: candidateId, parent_version_id: original.id, score_id: candidate.score_id, audio_asset_id: audio.id, inputs: body });
    await page.reload();
    await expect(page.locator('[data-version-id]')).toHaveAttribute('data-version-id', child.id);
    await page.getByText(t.snapshot, { exact: true }).click();
    await expect(page.locator('[data-submitted-abc]')).toHaveText(EDITED_ABC);
    await expect(page.getByRole('link', { name: t.source, exact: true })).toHaveAttribute('href', `/projects/${project.id}/scores/${selected}`);
    expect(received(await api.GET('/projects/{project_id}/versions/{version_id}', { params: { path: { ...path, version_id: original.id } } }))).toEqual(original);
    expect(received(await api.GET('/projects/{project_id}/assets/{asset_id}/content', { params: { path: { ...path, asset_id: score.abc_asset_id } }, parseAs: 'text' }))).toBe(ABC);
    expect(hash(new Uint8Array(received(await api.GET('/projects/{project_id}/assets/{asset_id}/content', { params: { path: { ...path, asset_id: original.audio_asset_id } }, parseAs: 'arrayBuffer' }))))).toBe(hash(new Uint8Array(originalAudio)));
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(theme === 'dark' ? 390 : 1440);
    expect(errors).toEqual([]);
    expect(requests.every(url => url.startsWith(baseURL!) || url.startsWith('blob:'))).toBe(true);
    await info.attach('selected-score-version-loop', { body: JSON.stringify({ scope: 'Production browser/FastAPI, controlled CPU test tone; no model quality claim', selected, body, job, candidate, original, child, audio }, null, 2), contentType: 'application/json' });
  });
}

test('editing while submission acknowledgement is held cannot change the actual Job or its resulting Candidate', async ({ page, baseURL }, info) => {
  const { api, project, score, original } = await withParent(baseURL);
  const selected = await selectEdited(page, project.id, score.id);
  await fillGeneration(page);
  let release!: () => void, committed!: (job: JobRead) => void;
  const held = new Promise<void>(resolve => { release = resolve; });
  const accepted = new Promise<JobRead>(resolve => { committed = resolve; });
  await page.route(`**/api/projects/${project.id}/jobs/generate-from-score`, async route => {
    const response = await route.fetch();
    committed(await response.json());
    await held;
    await route.fulfill({ response });
  });
  try {
    await page.getByRole('button', { name: 'Generate from selected Score', exact: true }).click();
    const submitted = await accepted;
    await expect(page.getByText('Waiting for the application to acknowledge this submission.', { exact: true })).toBeVisible();
    await page.getByRole('textbox', { name: 'ABC Score text', exact: true }).fill(NEXT_ABC);
    await page.getByRole('textbox', { name: 'Music style', exact: true }).fill('later drums, not submitted');
    await expect(page.getByText('Notation and MIDI match the current draft.', { exact: true })).toBeVisible();
    const expected = { abc: EDITED_ABC, source_score_id: selected, parent_version_id: original.id, style: STYLE, lyrics: LYRICS, seed: Number(SEED), max_seconds: 35 };
    expect(submitted.inputs).toEqual(expected);
    release();
    await expect(page.locator('.score-regeneration .job-monitor')).toHaveAttribute('data-job-id', submitted.id);
    await expect(page.locator('.candidate-detail .record-details code').filter({ hasText: submitted.id })).toHaveCount(1);
    await page.locator('.job-submitted-inputs').getByText('Submitted inputs', { exact: true }).click();
    await expect(page.locator('.job-submitted-inputs [data-submitted-abc]')).toHaveText(EDITED_ABC);
    await expect(page.getByRole('textbox', { name: 'ABC Score text', exact: true })).toHaveValue(NEXT_ABC);
    await expect(page.getByRole('button', { name: 'Generate from selected Score', exact: true })).toBeDisabled();
    const job = received(await api.GET('/projects/{project_id}/jobs/{job_id}', { params: { path: { project_id: project.id, job_id: submitted.id } } }));
    expect(job.inputs).toEqual(expected);
    expect(received(await api.GET('/projects/{project_id}/versions', { params: { path: { project_id: project.id } } }))).toEqual([original]);
    await info.attach('held-submit-frozen-input', { body: JSON.stringify({ selected, expected, job }, null, 2), contentType: 'application/json' });
  } finally { release(); }
});

test('empty, unselected, checking, invalid and changed drafts cannot be generated; invalid seed and blank style are rejected', async ({ page, baseURL }) => {
  const { api, project, score } = await seed(baseURL);
  await page.goto(`/projects/${project.id}/scores/${score.id}`);
  await page.locator('.preferences select').selectOption('en');
  const draft = page.getByRole('textbox', { name: 'ABC Score text', exact: true });
  const generate = page.getByRole('button', { name: 'Generate from selected Score', exact: true });
  await fillGeneration(page);
  await expect(page.getByText('Notation and MIDI match the current draft.', { exact: true })).toBeVisible();
  await expect(generate).toBeDisabled();
  await page.getByRole('button', { name: 'Select saved Score', exact: true }).click();
  await expect(generate).toBeEnabled();
  let release!: () => void, checked!: () => void;
  const held = new Promise<void>(resolve => { release = resolve; });
  const validationReached = new Promise<void>(resolve => { checked = resolve; });
  const validateURL = `**/api/projects/${project.id}/scores/validate`;
  await page.route(validateURL, async route => { const response = await route.fetch(); checked(); await held; await route.fulfill({ response }); });
  try {
    await draft.fill(EDITED_ABC);
    await validationReached;
    await expect(page.getByText('Checking draft…', { exact: true })).toBeVisible();
    await expect(generate).toBeDisabled();
    release();
    await expect(page.getByText('Notation and MIDI match the current draft.', { exact: true })).toBeVisible();
    await expect(generate).toBeDisabled();
  } finally { release(); await page.unroute(validateURL); }
  await draft.fill(ABC.replace('C D E F G2 E2', 'C ? E F G2 E2'));
  await expect(page.getByText('ABC needs correction', { exact: true })).toBeVisible();
  await expect(generate).toBeDisabled();
  await draft.fill('');
  await expect(page.getByText('ABC requires X: and K: headers and exactly one tune.', { exact: true })).toBeVisible();
  await expect(generate).toBeDisabled();
  await page.getByRole('button', { name: 'Restore original into draft', exact: true }).click();
  await expect(page.getByText('Notation and MIDI match the current draft.', { exact: true })).toBeVisible();
  await expect(page.locator('.selected-score')).toHaveAttribute('data-selected-score-id', score.id);
  await expect(generate).toBeEnabled();
  await page.getByRole('textbox', { name: 'Random seed', exact: true }).fill('-1');
  await generate.click();
  await expect(page.getByRole('alert')).toContainText('Enter an integer seed');
  await page.getByRole('textbox', { name: 'Random seed', exact: true }).fill(SEED);
  await page.getByRole('textbox', { name: 'Music style', exact: true }).fill('   ');
  await generate.click();
  await expect(page.getByRole('alert')).toContainText('Enter music style and lyrics.');
  expect(received(await api.GET('/projects/{project_id}/jobs', { params: { path: { project_id: project.id } } }))).toEqual([]);
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path: { project_id: project.id } } }))).toEqual([]);
});

test('missing generation capability preserves selected ABC and inputs until an explicit readiness recheck', async ({ page, baseURL }) => {
  const { project, score } = await seed(baseURL);
  const selected = await selectEdited(page, project.id, score.id);
  await fillGeneration(page);
  await control({ capability: 'missing' });
  await page.getByRole('button', { name: 'Check readiness again', exact: true }).click();
  await expect(page.getByText('Creation cannot start yet', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Generate from selected Score', exact: true })).toBeDisabled();
  await expect(page.getByRole('textbox', { name: 'ABC Score text', exact: true })).toHaveValue(EDITED_ABC);
  await expect(page.getByRole('textbox', { name: 'Music style', exact: true })).toHaveValue(STYLE);
  await expect(page.locator('.selected-score')).toHaveAttribute('data-selected-score-id', selected);
  await control({});
  await page.getByRole('button', { name: 'Check readiness again', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Generate from selected Score', exact: true })).toBeEnabled();
});

test('cancelled Score generation preserves editable input and an explicit retry creates a new Job with the cancelled snapshot', async ({ page, baseURL }, info) => {
  const { api, project, score } = await seed(baseURL);
  const selected = await selectEdited(page, project.id, score.id);
  await fillGeneration(page);
  await control({ scenario: 'hold' });
  await page.getByRole('button', { name: 'Generate from selected Score', exact: true }).click();
  await expect(page.getByText('Progress is unknown; showing the current phase', { exact: true })).toBeVisible();
  await expect(page.getByRole('progressbar')).toHaveCount(0);
  const first = await page.locator('.job-monitor').getAttribute('data-job-id');
  if (!first) throw new Error('No active Job');
  await page.getByRole('textbox', { name: 'ABC Score text', exact: true }).fill(NEXT_ABC);
  await page.getByRole('textbox', { name: 'Music style', exact: true }).fill('later style after cancellation');
  await page.getByRole('button', { name: 'Request cancellation', exact: true }).click();
  await expect(page.locator('.job-card .tag')).toHaveText('Cancelled');
  const path = { project_id: project.id };
  expect(received(await api.GET('/projects/{project_id}/candidates', { params: { path } }))).toEqual([]);
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([]);
  await control({});
  await page.getByRole('button', { name: 'Create a new retry job', exact: true }).click();
  await expect(page.locator('.job-monitor')).not.toHaveAttribute('data-job-id', first);
  await expect(page.locator('.candidate-detail')).toBeVisible();
  const jobs = received(await api.GET('/projects/{project_id}/jobs', { params: { path } }));
  expect(jobs).toHaveLength(2);
  const retry = jobs.find(value => value.id !== first);
  expect(retry).toMatchObject({ operation: 'GenerateFromScore', provenance: { retry_of_job_id: first }, inputs: { abc: EDITED_ABC, source_score_id: selected, parent_version_id: null, style: STYLE, lyrics: LYRICS, seed: Number(SEED), max_seconds: 35 } });
  await expect(page.getByRole('textbox', { name: 'ABC Score text', exact: true })).toHaveValue(NEXT_ABC);
  await expect(page.getByRole('textbox', { name: 'Music style', exact: true })).toHaveValue('later style after cancellation');
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([]);
  await info.attach('explicit-cancelled-job-retry', { body: JSON.stringify({ first, retry, jobs }, null, 2), contentType: 'application/json' });
});

test('inference failure keeps the original Version and earlier Candidate readable while preserving the current edit', async ({ page, baseURL }, info) => {
  const { api, project, score, original } = await withParent(baseURL);
  const selected = await selectEdited(page, project.id, score.id);
  await fillGeneration(page);
  await control({ scenario: 'runtime_out_of_memory' });
  await page.getByRole('button', { name: 'Generate from selected Score', exact: true }).click();
  await expect(page.locator('.job-problem')).toContainText('runtime_out_of_memory');
  await expect(page.locator('.candidate-detail')).toHaveAttribute('data-candidate-id', original.candidate_id);
  await expect(page.getByText('Previously completed Candidate', { exact: true })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'ABC Score text', exact: true })).toHaveValue(EDITED_ABC);
  await expect(page.locator('.selected-score')).toHaveAttribute('data-selected-score-id', selected);
  await expect(page.getByRole('textbox', { name: 'Lyrics', exact: true })).toHaveValue(LYRICS);
  const path = { project_id: project.id };
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([original]);
  expect(received(await api.GET('/projects/{project_id}/candidates', { params: { path } }))).toHaveLength(1);
  await control({});
  const posted = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/retry'));
  await page.getByRole('button', { name: 'Create a new retry job', exact: true }).click();
  const retried: JobRead = await (await posted).json();
  await expect(page.locator('.candidate-detail .record-details code').filter({ hasText: retried.id })).toHaveCount(1);
  expect(retried.inputs).toMatchObject({ abc: EDITED_ABC, source_score_id: selected, parent_version_id: original.id });
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([original]);
  await info.attach('failed-score-job-explicit-retry', { body: JSON.stringify({ original, retried }, null, 2), contentType: 'application/json' });
});

test('a lost initial generation acknowledgement survives reload and recovers the committed Job without resubmitting', async ({ page, baseURL }, info) => {
  const { api, project, score } = await seed(baseURL);
  const selected = await selectEdited(page, project.id, score.id);
  await fillGeneration(page);
  const writes: unknown[] = [];
  let accepted!: JobRead;
  const generateURL = `**/api/projects/${project.id}/jobs/generate-from-score`;
  await page.route(generateURL, async route => {
    writes.push(route.request().postDataJSON());
    const response = await route.fetch();
    accepted = await response.json();
    await route.abort('failed');
  });
  await page.getByRole('button', { name: 'Generate from selected Score', exact: true }).click();
  const recovery = page.locator('.submission-recovery');
  await expect(recovery).toContainText('Submission is unconfirmed');
  const expected = { abc: EDITED_ABC, source_score_id: selected, parent_version_id: null, style: STYLE, lyrics: LYRICS, seed: Number(SEED), max_seconds: 35 };
  expect(accepted.inputs).toEqual(expected);
  await page.getByRole('textbox', { name: 'ABC Score text', exact: true }).fill(NEXT_ABC);
  await page.getByRole('textbox', { name: 'Music style', exact: true }).fill('later unrelated style');
  await page.reload();
  await expect(recovery).toContainText('Submission is unconfirmed');
  await expect(page.getByRole('button', { name: 'Generate from selected Score', exact: true })).toBeDisabled();
  await expect(recovery.getByRole('button', { name: 'Start another explicit attempt after checking', exact: true })).toHaveCount(0);
  await recovery.getByText('Submitted inputs', { exact: true }).click();
  await expect(recovery.locator('[data-submitted-abc]')).toHaveText(EDITED_ABC);
  await expect(recovery.getByText(STYLE, { exact: true })).toBeVisible();
  await expect(recovery.getByRole('link', { name: 'Inspect submitted source Score', exact: true })).toHaveAttribute('href', `/projects/${project.id}/scores/${selected}`);
  await recovery.getByRole('button', { name: 'Read project jobs', exact: true }).click();
  await recovery.getByRole('button').filter({ hasText: accepted.id }).click();
  await expect(page.locator('.job-monitor')).toHaveAttribute('data-job-id', accepted.id);
  await expect(page.locator('.candidate-detail .record-details code').filter({ hasText: accepted.id })).toHaveCount(1);
  await page.reload();
  await expect(page.locator('.job-monitor')).toHaveAttribute('data-job-id', accepted.id);
  await expect(page.locator('.candidate-detail .record-details code').filter({ hasText: accepted.id })).toHaveCount(1);
  expect(writes).toEqual([expected]);
  const jobs = received(await api.GET('/projects/{project_id}/jobs', { params: { path: { project_id: project.id } } }));
  expect(jobs).toHaveLength(1);
  expect(jobs[0]).toMatchObject({ id: accepted.id, inputs: expected });
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path: { project_id: project.id } } }))).toEqual([]);
  await info.attach('lost-generation-ack-recovered-job', { body: JSON.stringify({ writes, accepted, jobs }, null, 2), contentType: 'application/json' });
});

test('an unconfirmed generation with no committed Job requires explicit Jobs readback and a new user submission', async ({ page, baseURL }) => {
  const { api, project, score } = await seed(baseURL);
  await selectEdited(page, project.id, score.id);
  await fillGeneration(page);
  let posts = 0;
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/jobs/generate-from-score')) posts++; });
  const generateURL = `**/api/projects/${project.id}/jobs/generate-from-score`;
  await page.route(generateURL, route => route.abort('failed'));
  await page.getByRole('button', { name: 'Generate from selected Score', exact: true }).click();
  const recovery = page.locator('.submission-recovery');
  await expect(recovery).toContainText('Submission is unconfirmed');
  await expect(recovery.getByRole('button', { name: 'Start another explicit attempt after checking', exact: true })).toHaveCount(0);
  const path = { project_id: project.id };
  expect(received(await api.GET('/projects/{project_id}/jobs', { params: { path } }))).toEqual([]);
  await recovery.getByRole('button', { name: 'Read project jobs', exact: true }).click();
  await expect(recovery).toContainText('No generation job was read.');
  await recovery.getByRole('button', { name: 'Start another explicit attempt after checking', exact: true }).click();
  await expect(recovery).toHaveCount(0);
  expect(posts).toBe(1);
  expect(received(await api.GET('/projects/{project_id}/jobs', { params: { path } }))).toEqual([]);
  await page.unroute(generateURL);
  await generateCandidate(page);
  expect(posts).toBe(2);
  expect(received(await api.GET('/projects/{project_id}/jobs', { params: { path } }))).toHaveLength(1);
});

test('Version persistence failure keeps Candidate and inputs and retries the first name despite later edits', async ({ page, baseURL }, info) => {
  const { api, project, score, original } = await withParent(baseURL);
  const selected = await selectEdited(page, project.id, score.id);
  const candidate = await generateCandidate(page);
  const path = { project_id: project.id };
  const writes: unknown[] = [];
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/versions')) writes.push(request.postDataJSON()); });
  await page.getByRole('textbox', { name: 'Version name', exact: true }).fill('First name after storage failure');
  await writeFile(resolve(runDir!, 'fail-version-save'), 'owned CPU test fault');
  await page.getByRole('button', { name: 'Save as a version', exact: true }).click();
  await expect(page.locator('.save-candidate .error-box')).toContainText('version_commit_unconfirmed');
  expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([original]);
  await expect(page.locator('.candidate-detail')).toHaveAttribute('data-candidate-id', candidate);
  await expect(page.getByRole('textbox', { name: 'ABC Score text', exact: true })).toHaveValue(EDITED_ABC);
  await page.getByRole('textbox', { name: 'Version name', exact: true }).fill('Later name cannot replace captured intent');
  await page.getByRole('button', { name: 'Save the same version again', exact: true }).click();
  await expect(page.getByRole('link', { name: 'View saved version', exact: true })).toBeVisible();
  const versions = received(await api.GET('/projects/{project_id}/versions', { params: { path } }));
  expect(versions).toHaveLength(2);
  const child = versions.find(value => value.id !== original.id);
  expect(child).toMatchObject({ candidate_id: candidate, name: 'First name after storage failure', parent_version_id: original.id, inputs: { abc: EDITED_ABC, source_score_id: selected } });
  expect(writes).toEqual([{ candidate_id: candidate, name: 'First name after storage failure' }, { candidate_id: candidate, name: 'First name after storage failure' }]);
  await info.attach('storage-failure-captured-save', { body: JSON.stringify({ writes, original, child }, null, 2), contentType: 'application/json' });
});
