import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { createMusicClient } from '@llm-music/api-client';
import { test, expect } from '@playwright/test';
import { hash, labels, inputs, completedCandidate, mediaState, control, received } from './generation-fixtures.js';

test.beforeEach(async () => { await control({}); });

for (const locale of ['zh-CN', 'en'] as const) for (const theme of ['light', 'dark'] as const) {
  test(`${locale}/${theme}: public generation, actual player clock, region, explicit saved version and refresh`, async ({ page, baseURL }, info) => {
    if (!baseURL) throw new Error('No owned Web URL');
    const api = createMusicClient({ baseUrl: `${baseURL}/api` });
    const t = labels[locale];
    const errors: string[] = [], requests: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => requests.push(request.url()));
    const project = received(await api.POST('/projects', { body: { name: `听晨光 · ${randomUUID().slice(0, 8)}` } }));
    const path = { project_id: project.id };
    await page.goto(`/projects/${project.id}`);
    await page.getByRole('combobox').selectOption(locale);
    if (theme === 'dark') await page.locator('.preferences button').click();
    await expect(page.getByRole('heading', { name: locale === 'en' ? 'No reference audio yet' : '还没有参考音频' })).toBeVisible();
    await page.locator('.tabs').getByRole('link', { name: locale === 'en' ? 'Scores' : '乐谱', exact: true }).click();
    await expect(page.getByRole('heading', { name: locale === 'en' ? 'No score to inspect yet' : '还没有可以查看的乐谱' })).toBeVisible();
    await page.getByRole('link', { name: t.generateTab, exact: true }).click();
    await expect(page.getByRole('heading', { name: locale === 'en' ? 'No candidate music yet' : '还没有候选音乐' })).toBeVisible();
    await inputs(page, locale);
    // Preferences preserve live text and the form identity.
    await page.getByRole('combobox').selectOption(locale === 'en' ? 'zh-CN' : 'en');
    await page.locator('.preferences button').click();
    await page.getByRole('combobox').selectOption(locale);
    await page.locator('.preferences button').click();
    await expect(page.getByRole('textbox', { name: t.seed, exact: true })).toHaveValue('2026192201');
    await page.getByRole('textbox', { name: t.seed, exact: true }).fill('9007199254740992');
    await page.getByRole('button', { name: t.submit }).click();
    await expect(page.getByRole('alert')).toContainText('9007199254740991');
    expect(received(await api.GET('/projects/{project_id}/jobs', { params: { path } }))).toHaveLength(0);
    await page.getByRole('textbox', { name: t.seed, exact: true }).fill('2026192201');
    const candidateId = await completedCandidate(page, locale);
    const candidate = received(await api.GET('/projects/{project_id}/candidates/{candidate_id}', { params: { path: { ...path, candidate_id: candidateId } } }));
    expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([]);
    expect(candidate.inputs).toMatchObject({ seed: 2026192201, max_seconds: 35 });
    const asset = received(await api.GET('/projects/{project_id}/assets/{asset_id}', { params: { path: { ...path, asset_id: candidate.audio_asset_id } } }));
    const audioBytes = received(await api.GET('/projects/{project_id}/assets/{asset_id}/content', { params: { path: { ...path, asset_id: asset.id } }, parseAs: 'arrayBuffer' }));
    expect(hash(new Uint8Array(audioBytes))).toBe(asset.sha256);
    await page.getByRole('button', { name: t.listen }).click();
    const player = page.locator('#persistent-player');
    await expect(player.getByRole('button', { name: t.play, exact: true })).toBeEnabled();
    await expect(page.locator('audio')).toHaveCount(1);
    await expect.poll(async () => (await mediaState(page)).duration).toBeCloseTo(asset.duration_seconds!, 1);
    await player.getByRole('button', { name: t.play, exact: true }).click();
    await expect.poll(async () => (await mediaState(page)).time).toBeGreaterThan(0.15);
    const before = (await mediaState(page)).time;
    await page.getByRole('combobox').selectOption(locale === 'en' ? 'zh-CN' : 'en');
    await page.locator('.preferences button').click();
    await page.getByRole('combobox').selectOption(locale);
    await page.locator('.preferences button').click();
    expect((await mediaState(page)).paused).toBe(false);
    await page.getByRole('link', { name: t.lyricsTab, exact: true }).click();
    await expect.poll(async () => (await mediaState(page)).time).toBeGreaterThan(before);
    expect((await mediaState(page)).paused).toBe(false);
    await page.getByRole('link', { name: t.versionsTab, exact: true }).click();
    expect((await mediaState(page)).paused).toBe(false);
    await page.getByRole('link', { name: t.generateTab, exact: true }).click();
    await expect(page.getByRole('textbox', { name: t.style, exact: true })).toHaveValue(candidate.inputs.style);
    await page.locator('.tabs').getByRole('link', { name: locale === 'en' ? 'Creative jobs' : '创作任务', exact: true }).click();
    const beforeResult = (await mediaState(page)).time;
    await page.getByRole('link', { name: locale === 'en' ? 'Listen to generated results' : '试听生成结果', exact: true }).click();
    await expect(page).toHaveURL(new RegExp(`generate\\?jobId=${candidate.job_id}`));
    await expect.poll(async () => (await mediaState(page)).time).toBeGreaterThan(beforeResult);
    expect((await mediaState(page)).paused).toBe(false);
    await page.locator('.tabs').getByRole('link', { name: locale === 'en' ? 'Scores' : '乐谱', exact: true }).click();
    await expect(page.locator(`a[href$="/scores/${candidate.score_id}"]`)).toBeVisible();
    await page.getByRole('link', { name: t.generateTab, exact: true }).click();
    await page.getByRole('link', { name: t.score, exact: true }).click();
    await expect(page).toHaveURL(new RegExp(candidate.score_id));
    await expect(page.locator('audio')).toHaveCount(1);
    expect((await mediaState(page)).paused).toBe(false);
    await player.getByRole('button', { name: t.pause, exact: true }).click();
    const seek = player.getByRole('slider', { name: t.seek });
    await seek.focus(); await seek.press('End');
    await expect.poll(async () => (await mediaState(page)).time).toBeGreaterThan(34);
    await seek.press('Home');
    await expect.poll(async () => (await mediaState(page)).time).toBeLessThan(0.2);
    await player.getByText(t.region, { exact: true }).click();
    await player.getByLabel(t.start, { exact: true }).fill('1');
    await player.getByLabel(t.end, { exact: true }).fill('40');
    await player.getByRole('button', { name: t.apply }).click();
    await expect(player.getByRole('alert')).toHaveText(t.invalidRegion);
    await player.getByLabel(t.start, { exact: true }).fill('0.2');
    await player.getByLabel(t.end, { exact: true }).fill('0.9');
    await player.getByRole('button', { name: t.apply }).click();
    await player.getByRole('button', { name: t.playRegion }).click();
    await expect.poll(async () => { const state = await mediaState(page); return { time: state.time, paused: state.paused }; }).toEqual({ time: 0.9, paused: true });
    await page.getByRole('link', { name: t.generateTab, exact: true }).click();
    const intent = { candidate_id: candidateId, name: '晨光 · 留下这一次' };
    await page.getByRole('textbox', { name: t.name, exact: true }).fill(intent.name);
    const firstSave = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/versions'));
    await page.getByRole('button', { name: t.save, exact: true }).click();
    expect((await firstSave).status()).toBe(201);
    await page.getByRole('link', { name: t.saved }).click();
    const versions = received(await api.GET('/projects/{project_id}/versions', { params: { path } }));
    expect(versions).toHaveLength(1);
    const original = versions[0]!;
    const repeated = await api.POST('/projects/{project_id}/versions', { params: { path }, body: intent });
    expect(repeated.response.status).toBe(200); expect(received(repeated)).toEqual(original);
    await page.getByRole('link', { name: locale === 'en' ? 'Reference audio and assets' : '参考音频与素材', exact: true }).click();
    await expect(page.locator('.asset-list button').filter({ hasText: asset.original_name })).toBeVisible();
    await page.getByRole('link', { name: t.versionsTab, exact: true }).click();
    await page.getByRole('link', { name: locale === 'en' ? 'View version' : '查看版本', exact: true }).click();
    await page.reload();
    await expect(page.locator('[data-version-id]')).toHaveAttribute('data-version-id', original.id);
    await expect(page.getByRole('heading', { name: intent.name })).toBeVisible();
    await page.getByRole('link', { name: locale === 'en' ? 'Reference audio and assets' : '参考音频与素材', exact: true }).click();
    await page.locator('.asset-list button').filter({ hasText: asset.original_name }).click();
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: locale === 'en' ? 'Download original file' : '下载原文件' }).click();
    const download = await downloadPromise;
    expect(await download.failure()).toBeNull();
    const downloadedPath = await download.path();
    if (!downloadedPath) throw new Error('Native generated audio download did not finish');
    expect(hash(await readFile(downloadedPath))).toBe(asset.sha256);
    await page.getByRole('link', { name: t.generateTab, exact: true }).click();
    await inputs(page, locale, ' · 第二次');
    const second = await completedCandidate(page, locale);
    expect(second).not.toBe(candidateId);
    expect(received(await api.GET('/projects/{project_id}/versions/{version_id}', { params: { path: { ...path, version_id: original.id } } }))).toEqual(original);
    expect(received(await api.GET('/projects/{project_id}/versions', { params: { path } }))).toEqual([original]);
    expect(hash(new Uint8Array(received(await api.GET('/projects/{project_id}/assets/{asset_id}/content', { params: { path: { ...path, asset_id: asset.id } }, parseAs: 'arrayBuffer' }))))).toBe(asset.sha256);
    expect(errors).toEqual([]);
    expect(requests.every(url => url.startsWith(baseURL) || url.startsWith('blob:'))).toBe(true);
    await info.attach('public-identities-and-bytes', { body: JSON.stringify({ scope: 'real Chromium + production FastAPI + controlled CPU FakeRuntime test tone; no GPU music-quality claim', candidate, original, audio_sha256: asset.sha256, duration: asset.duration_seconds }, null, 2), contentType: 'application/json' });
    await page.screenshot({ path: info.outputPath(`${locale}-${theme}.png`), fullPage: true });
  });
}

